export const CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG";
export const CHANGE_FULL_SCREEN = "player/CHANGE_FULL_SCREEN";
export const CHANGE_PLAYING = "player/CHANGE_PLAYING";
export const CHANGE_SEQUENCE_PLAYLIST = "player/CHANGE_SEQUENCE_PLAYLIST";
export const CHANGE_PLAYLIST = "player/CHANGE_PLAYLIST";
export const CHANGE_CURRENT_INDEX = "player/CHANGE_CURRENT_INDEX";
export const CHANGE_MODE = "player/CHANGE_MODE";
export const CHANGE_SHOW_PLAYLIST = "player/CHANGE_SHOW_PLAYLIST";
