export const CHANGE_SINGERS_DETAIL_ARTIST =
  "singer-detail/CHANGE_SINGERS_DETAIL_ARTIST";
export const CHANGE_SINGERS_DETAIL_LOADING =
  "singer-detail/CHANGE_SINGERS_DETAIL_LOADING";
export const CHANGE_SINGERS_DETAIL_SONGS_ARTIST =
  "singer-detail/CHANGE_SINGERS_DETAIL_SONGS_ARTIST";
